version: 2
jobs:
  release:
    docker:
      - image: docker:stable
    steps:
      - run: apk add --no-cache openssh-client git
      - checkout
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: docker build -t p3lim/alpine:latest -t p3lim/alpine:$CIRCLE_TAG .
      - run: docker push p3lim/alpine:$CIRCLE_TAG
      - run: docker push p3lim/alpine:latest
workflows:
  version: 2
  release:
    jobs:
      - release:
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
