#!/usr/bin/with-contenv bash

echo '--------------------------------------'
echo
echo -e '              \033[0m\033[36m   /\\ /\\' ""
echo -e '                /\033[0m\033[34m/ \033[0m\033[36m\\  \\'
echo -e '               /\033[0m\033[34m/   \033[0m\033[36m\\  \\'
echo -e '              /\033[0m\033[34m//    \033[0m\033[36m\\  \\'
echo -e '              \033[0m\033[34m//      \033[0m\033[36m\\  \\'
echo -e '                       \\\033[0m'
echo
echo "Alpine Linux $(cat /etc/alpine-release) w/ s6-overlay"
echo 'https://github.com/p3lim/docker-alpine'
echo '--------------------------------------'
echo
